SPL: add the symbol _u_boot_list_env_clbk_* in u-boot-spl.lds
Compiled for SPL, there was link error:
env_callback.c:38: undefined reference to `_u_boot_list_env_clbk__start'
env_callback.c:38: undefined reference to `_u_boot_list_env_clbk__end'

Because there don't generate callback list entries for SPL and no
function with these symbol was called, so add the symbol
u_boot_list_env_clbk__* in u-boot-spl.lds to eliminate the error.

Signed-off-by: Ying Zhang <b40530@freescale.com>
Change-Id: I07c106e4325178b96cd8775d0cc382843c392bf7
Reviewed-on: http://git.am.freescale.net:8181/5614
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Yusong Sun <yorksun@freescale.com>