fsl_ifc: fix compile error for missing IFC BANK
There's no IFC controller instead of eLBC controller on some platforms,
such as MPC8536, P2041, P3041, P4080 etc, so there's no macro definition
for the number of IFC chip select(CONFIG_SYS_FSL_IFC_BANK_COUNT) which
is used in the IFC controller header file fsl_ifc.h on these platforms.

The following compile errors will be run into:
u-boot-devel/include/asm/fsl_ifc.h:923:2: error: #error IFC BANK count
not defined
make[1]: *** No rule to make target `.depend', needed by `all'.  Stop.
make[1]: Leaving directory
`/home/hmk/sdk/u-boot-devel/nand_spl/board/freescale/mpc8536ds'
make: *** [nand_spl] Error 2

Signed-off-by: Mingkai Hu <Mingkai.hu@freescale.com>